#!/bin/bash

set -eux

# https://medium.com/microscaling-systems/labelling-automated-builds-on-docker-hub-f3d073fb8e1#.yldbwesu7

CURDIR=$(dirname $0)

if [ -z "${IMAGE_NAME}" ]; then
    echo ! "IMAGE_NAME" variable missing.
    echo eg. IMAGE_NAME="dehy/adminer:local" sh $0
    exit 1
fi

function evil_git_dirty {
    [[ $(git diff --shortstat 2> /dev/null | tail -n1) != "" ]] && echo "-dirty"
}

VCS_REF=$(git rev-parse --short HEAD)$(evil_git_dirty)
BUILD_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

version_search_pattern="\s*\* @version "
VERSION=$(grep -E "^${version_search_pattern}" rootfs/var/www/html/adminer.php | sed -E -e "s/${version_search_pattern}//")

docker build --build-arg VCS_REF=${VCS_REF} \
             --build-arg BUILD_DATE=${BUILD_DATE} \
             --build-arg VERSION=${VERSION} \
             -t $IMAGE_NAME .
